const sampleBooks = [
  {
    title: "My Fault",
    author: "Mercedes ron",
    description:"My Fault (Culpable #1) by Mercedes Ron is a popular YA romance about 17-year-old Noah, whose life is upended when her mom marries a billionaire, forcing them to move to L.A. and live with her new, arrogant, bad-boy stepbrother, Nick, leading to a fiery enemies-to-lovers story filled with forbidden attraction, illegal street racing, secrets, and trauma. It's known for its angst, drama, and themes of love, danger, and healing, becoming a viral sensation on BookTok and Wattpad. ",
    image: "https://i.pinimg.com/736x/dc/5b/c1/dc5bc1d71e8380b2319c2b5ad5a99989.jpg",
    price: 399,
    releasedate: new Date("2023-06-06"),
    country: "United States",
    genre: "Romance",
    pages: 496,
  },
  {
    title: "Does It Hurt?",
    author: "H. D. Carlton",
    description:"A dark, emotional romance where a girl who has lost everything is drawn into a dangerous, obsessive relationship with a mysterious man who both protects and torments her while they struggle to survive after being stranded together.",
    image: "https://i.pinimg.com/736x/15/2a/5f/152a5f0631b392a9ca798b578ec7927d.jpg",
    price: 499,
    releasedate: new Date("2022-07-15"),
    country: "United States",
    genre: "Dark Romance",
    pages: 430,
  },
  {
    title: "It ends with us",
    author: "Collen Hoover",
    description:"It Ends with Us follows Lily Bloom, who starts a flower shop in Boston, meets charismatic neurosurgeon Ryle Kincaid, and falls for him, but their intense romance turns abusive as Ryle's anger surfaces, intensified by the reappearance of Lily's first love, Atlas Corrigan; pregnant and realizing she's repeating her mother's cycle of abuse, Lily chooses to leave Ryle, ending the violence for her daughter and eventually reconnecting with Atlas, ready for a new beginning.",
    image: "https://i.pinimg.com/736x/2b/67/60/2b6760353435b8ef1a3437385a381039.jpg",
    price: 299,
    releasedate: new Date("2016-08-02"),
    country: "United States",
    genre: "Romance",
    pages: 376,
  },
  {
    title: "It Starts With Us",
    author: "Colleen Hoover",
    description: "A deeply emotional romance that continues the story from It Ends With Us, focusing on Lily and her first love Atlas as they navigate co-parenting, rekindle their connection, and face past wounds while finding hope and second chances together.",
    image: "https://i.pinimg.com/736x/37/35/8d/37358dff161c09e09b7ee7b6d86e180b.jpg", 
    price: 499,
    releasedate: new Date("2022-10-18"),
    country: "United States",
    genre: "Romance",
    pages: 336
  },
  {
    title: "The Love Hypothesis",
    author: "Ali Hazelwood",
    description: "A witty, heartfelt romance about a PhD student who pretends to date a grumpy professor to convince her best friend she’s over her ex, only to discover that their fake relationship might be real.",
    image: "https://i.pinimg.com/1200x/ae/aa/53/aeaa53b995d12762324bafb27912a964.jpg",
    price: 249,
    releasedate: new Date("2021-09-14"),
    country: "United States",
    genre: "Romance",
    pages: 376
  },
  {
    title: "One of Us Is Lying",
    author: "Karen M. McManus",
    description: "A gripping YA mystery where five students walk into detention and only four come out alive, leaving secrets, lies, and a shocking investigation that keeps readers guessing.",
    image: "https://i.pinimg.com/736x/6f/51/73/6f5173b7234c3d038d06e849f7b46ebe.jpg", 
    price: 450,
    releasedate: new Date("2017-05-29"),
    country: "United States",
    genre: "Mystery",
    pages: 368
  },
  {
    title: "Paper Towns",
    author: "John Green",
    description: "A clever coming-of-age mystery where Quentin Jacobsen searches for the enigmatic Margo Roth Spiegelman after she disappears, decoding clues that lead him (and friends) on a transformative adventure.",
    image: "https://i.pinimg.com/736x/03/11/19/0311194a9a8c9ebf76ae22e5cfa0888c.jpg",
    price: 499,
    releasedate: new Date("2008-10-16"),
    country: "United States",
    genre: "Mystery",
    pages: 305
  },
 {
    title: "Ikigai: The Japanese Secret to a Long and Happy Life",
    author: "Héctor García & Francesc Miralles",
    description: "A bestselling self-help book that explores the Japanese concept of ikigai — a reason for living — and offers insights into living a purposeful, joyful, and balanced life.",
    image: "https://i.pinimg.com/1200x/e3/26/b9/e326b92ced0cac7932bf9cc3b6f31259.jpg",
    price: 550,
    releasedate: new Date("2017-09-01"),
    country: "Spain",
    genre: "Self-Help",
    pages: 208
 },
 {
  title: "Turtles All the Way Down",
  author: "John Green",
  description: "A moving contemporary novel about a young woman navigating friendship, mental illness, and the mystery of a missing billionaire while confronting her own anxieties.",
  image: "https://i.pinimg.com/736x/75/53/9a/75539a6732152fad072c51069bac4285.jpg",
  price: 499,
  releasedate: new Date("2017-10-10"),
  country: "United States",
  genre: "Young Adult",
  pages: 304
},
{
  title: "I Want to Eat Your Pancreas",
  author: "Yoru Sumino",
  description: "A tender Japanese novel about a reserved high school boy whose life changes when he meets a cheerful classmate battling a terminal illness, leading to an unforgettable friendship.",
  image: "https://i.pinimg.com/1200x/ad/74/ff/ad74ffd0e0b2e4115edfe88e08421c92.jpg",
  price: 349,
  releasedate: new Date("2017-02-14"),
  country: "Japan",
  genre: "Romance",
  pages: 208
},
{
  title: "The Power of Your Subconscious Mind",
  author: "Joseph Murphy",
  description: "A classic self-help book exploring how to unlock the power of your subconscious to improve health, success, and happiness through positive thinking and mental programming.",
  image: "https://i.pinimg.com/736x/d0/65/e9/d065e9208c2df88505e2004d375dab1c.jpg",
  price: 399,
  releasedate: new Date("1963-01-01"),
  country: "United States",
  genre: "Self-Help",
  pages: 336
},
{
  title: "November 9",
  author: "Colleen Hoover",
  description: "A powerful contemporary romance about a chance meeting that leads to a yearly connection on the same date, exploring love, fate, and personal growth.",
  image: "https://i.pinimg.com/736x/83/11/01/83110146e860ecc1aa011e6caaa8661f.jpg",
  price: 499,
  releasedate: new Date("2015-11-10"),
  country: "United States",
  genre: "Romance",
  pages: 304
},
{
  title: "Verity",
  author: "Colleen Hoover",
  description: "A chilling romantic thriller about a struggling writer who uncovers disturbing truths while completing another author’s manuscript, blurring lines between fiction and reality.",
  image: "https://i.pinimg.com/736x/48/24/16/4824167e6495f00dca15b47e3c76200b.jpg",
  price: 549,
  releasedate: new Date("2018-12-18"),
  country: "United States",
  genre: "Thriller",
  pages: 336
},
{
    title: "Gothikana",
    author: "RunyX",
    description: "A gothic dark romance set in a mysterious academy where students vanish and secrets of the castle unfold with danger, love, and suspense.",
    image: "https://i.pinimg.com/736x/d4/85/63/d4856324f29c5f9eae4b69b4e38ce9cd.jpg",
    price: 399,
    releasedate: new Date("2021-06-15"),
    country: "Unknown/Indie",
    genre: "Gothic Romance",
    pages: 456
  },
  {
    title: "One of Us Is Next",
    author: "Karen M. McManus",
    description: "A mystery thriller where Bayview High students face deadly consequences in a game of truth or dare, following the original One of Us Is Lying story. :contentReference[oaicite:0]{index=0}",
    image: "https://i.pinimg.com/736x/e7/bb/44/e7bb445f905346195b6e8224cf85e317.jpg",
    price: 450,
    releasedate: new Date("2020-01-07"),
    country: "United States",
    genre: "Mystery",
    pages: 384
  },
  {
  title: "The Cousins",
  author: "Karen M. McManus",
  description: "Three estranged cousins are summoned to spend the summer at their wealthy grandmother’s island resort, where family secrets, betrayals, and dark mysteries begin to unravel as they search for the truth about their past.",
  image: "https://i.pinimg.com/736x/aa/ba/53/aaba531753f7846170eca3bedbca6c4b.jpg",
  price: 450,
  releasedate: new Date("2020-12-01"),
  country: "United States",
  genre: "Mystery",
  pages: 336
},
{
    title: "A Good Girl's Guide to Murder",
    author: "Holly Jackson",
    description: "A teen true-crime enthusiast investigates a murder-suicide, uncovering hidden truths and putting herself in danger. :contentReference[oaicite:1]{index=1}",
    image: "https://i.pinimg.com/736x/31/04/73/310473bfe2a435f89347a01cb1d1bc39.jpg",
    price: 499,
    releasedate: new Date("2019-05-02"),
    country: "United Kingdom",
    genre: "Mystery",
    pages: 352
  },
  {
    title: "The Fault in Our Stars",
    author: "John Green",
    description: "A moving YA romance about two teens with cancer who find love while confronting life, hope and loss. :contentReference[oaicite:4]{index=4}",
    image: "https://i.pinimg.com/1200x/54/50/8b/54508b92f052a417dabf8bdcf2dabbb2.jpg",
    price: 499,
    releasedate: new Date("2012-01-10"),
    country: "United States",
    genre: "Young Adult",
    pages: 313
  },
  {
  title: "Runaway Girl",
  author: "Emma Tallon",
  description: "Anna Davis has spent years terrified of her sadistic gangster boyfriend and finally runs away in the dead of night. As she begins a new life in London, she meets new friends and danger follows her, leading to a gripping crime thriller full of twists, betrayals, and survival against all odds.", 
  image: "https://i.pinimg.com/736x/f8/43/ee/f843ee319b9e07c17c064dafd3b81a00.jpg",
  price: 499,
  releasedate: new Date("2021-01-07"),
  country: "United Kingdom",
  genre: "Crime Thriller",
  pages: 352
},
{
  title: "Dear John",
  author: "Nicholas Sparks",
  description: "A poignant romance about a young soldier, John Tyree, who falls in love with college student Savannah Curtis during a brief leave. Their deep connection faces the strains of long‑distance and duty when John reenlists after 9/11, leading to heartbreaking choices, sacrifice, and the enduring power of love and memory. :contentReference[oaicite:0]{index=0}",
  image: "https://i.pinimg.com/736x/5b/ca/17/5bca17ed12fdf382f1d57d99dbf91fbc.jpg",
  price: 499,
  releasedate: new Date("2007-08-07"),
  country: "United States",
  genre: "Romance",
  pages: 237
},
{
  title: "Reminders of Him",
  author: "Colleen Hoover",
  description: "After serving five years in prison for a tragic mistake, Kenna Rowan returns home hoping to reunite with her young daughter, but faces judgment, resentment, and closed doors. As she works to rebuild her life and earn forgiveness, she forms a fragile connection with Ledger Ward, a local bar owner who becomes her unexpected ally in healing and love.",  
  image: "https://i.pinimg.com/736x/30/e6/f8/30e6f8aeb37980b6cf86c6a621d29bf2.jpg",
  price: 499,
  releasedate: new Date("2022-01-18"),
  country: "United States",
  genre: "Romance",
  pages: 336
},
{
    title: "Good Girl, Bad Blood",
    author: "Holly Jackson",
    description: "The sequel to A Good Girl's Guide to Murder with Pip solving a new disappearance while facing dark secrets. :contentReference[oaicite:2]{index=2}",
    image: "https://i.pinimg.com/736x/b7/ee/50/b7ee507f9e9aa28a704928a05990cacc.jpg",
    price: 499,
    releasedate: new Date("2020-05-07"),
    country: "United Kingdom",
    genre: "Mystery",
    pages: 432
  },
  {
  title: "The Mindfuck Series",
  author: "S.T. Abby",
  description: "A dark, intense psychological thriller and dark romance saga about trauma, revenge, and twisted love. Lana Myers, shaped by a horrific past, becomes a lethal force seeking justice while an FBI profiler drawn to her faces difficult choices as their dangerous attraction blurs lines between love and vengeance. The story weaves suspenseful crime, emotional conflict, and chilling twists throughout the series.",  
  image: "https://i.pinimg.com/1200x/f4/25/a0/f425a0a70b0a77d8803788d441fedee2.jpg",
  price: 285,
  releasedate: new Date("2022-01-01"),
  country: "India",
  genre: "Psychological Thriller",
  pages: 500
},
{
  title: "A Court of Thorns and Roses",
  author: "Sarah J. Maas",
  description: "Feyre Archeron, a teenage huntress, kills what she believes is a wolf in the woods and is dragged into the faerie lands of Prythian as punishment. There, she learns that her captor is a powerful faerie lord and discovers a dangerous world of magic, passion, and looming curses that she must confront to save both her own life and the world she’s come to care for.",
  image: "https://i.pinimg.com/1200x/ee/06/da/ee06da4b1bb681c5b9e9bc03b0d9f7ae.jpg",
  price: 599,
  releasedate: new Date("2015-05-05"),
  country: "United States",
  genre: "Fantasy Romance",
  pages: 448
},
{
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    description: "A powerful story of friendship and redemption set against Afghan history and upheaval.",
    image: "https://i.pinimg.com/1200x/84/da/f9/84daf9f004c6e83ad05d5fa96ac68d03.jpg",
    price: 599,
    releasedate: new Date("2003-05-29"),
    country: "United States",
    genre: "Historical Fiction",
    pages: 371
  },
   {
    title: "Twisted Love",
    author: "Ana Huang",
    description: "A passionate contemporary romance where Ava Chen and her brother’s enigmatic best friend Alex Volkov go from mutual disdain to an intense, complicated connection that defies all their expectations.",
    image: "https://i.pinimg.com/1200x/dd/4f/b2/dd4fb256f289918399a59c6c6b0c144f.jpg",
    price: 399,
    releasedate: new Date("2021-04-22"),
    country: "United States",
    genre: "Romance",
    pages: 320
  },
  {
    title: "The Duff",
    author: "Kody Keplinger",
    description: "A witty YA romance about a teen confronting labels, self-worth, and unexpected love.",
    image: "https://i.pinimg.com/736x/34/9c/10/349c10d63496ca71ede90fa2b1fffc1c.jpg",
    price: 399,
    releasedate: new Date("2010-09-14"),
    country: "United States",
    genre: "Young Adult Romance",
    pages: 352
  },
  {
  title: "Unhooked & Unbooked",
  author: "Dr. Aditya R. Nighhot",
  description: "A contemporary romance about four individuals with vastly different lives — a superstar singer, a struggling model, a social media influencer, and a devoted friend — whose paths collide and change forever as they navigate love, ego, heartbreak and self‑discovery in the modern world.",
  image: "https://m.media-amazon.com/images/I/61yyhegrEdL._SL1500_.jpg",
  price: 249,
  releasedate: new Date("2021-07-21"),
  country: "India",
  genre: "Romance",
  pages: 298
},
{
    title: "As Good as Dead",
    author: "Holly Jackson",
    description: "The third in the AGGGTM series where Pip faces a stalker and must uncover the truth before it’s too late. :contentReference[oaicite:3]{index=3}",
    image: "https://i.pinimg.com/736x/a3/80/d3/a380d39eed04fff0032547805ad4e37f.jpg",
    price: 499,
    releasedate: new Date("2021-07-08"),
    country: "United Kingdom",
    genre: "Thriller",
    pages: 384
  },
  {
    title: "An Abundance of Katherines",
    author: "John Green",
    description: "A hilarious YA tale following a prodigy who’s been dumped nineteen times — all by girls named Katherine — on a road trip of self-discovery. :contentReference[oaicite:6]{index=6}",
    image: "https://i.pinimg.com/736x/94/64/5f/94645fac1f200ae496774e4d449c27a4.jpg",
    price: 450,
    releasedate: new Date("2006-09-25"),
    country: "United States",
    genre: "Young Adult",
    pages: 288
  },
  {
    title: "Twisted Games",
    author: "Ana Huang",
    description: "A slow‑burn romance between Bridget von Ascheberg, a reluctant royal, and her determined bodyguard Rhys, whose protectiveness and emotional walls slowly give way to deeper feelings.",
    image: "https://i.pinimg.com/736x/30/e2/bc/30e2bc0e4cb59bf8c4b9255d247f7faf.jpg",
    price: 399,
    releasedate: new Date("2021-10-15"),
    country: "United States",
    genre: "Romance",
    pages: 340
  },
  {
    title: "Twisted Hate",
    author: "Ana Huang",
    description: "An enemies‑to‑lovers narrative where sharp‑tongued Jules Ambrose and charming doctor Josh Chen find their fiery rivalry evolving into unexpected attraction and longing.",
    image: "https://i.pinimg.com/736x/9f/ad/40/9fad40b5668374c4eaf68ef9e9b429ba.jpg",
    price: 399,
    releasedate: new Date("2022-01-27"),
    country: "United States",
    genre: "Romance",
    pages: 360
  }
];

module.exports = { data: sampleBooks };